"use client";
import {useMemo,useState} from "react";

type Listing={id:string;approved_price_crc:number;condition:string;finish:string;quantity:number;card_printings:{canonical_name:string;set_name:string;collector_number:string;language:string;game:string;stock_image_url:string|null}|null};
export default function Catalog({initial}:{initial:Listing[]}){
 const [query,setQuery]=useState(""); const [game,setGame]=useState("all"); const [cart,setCart]=useState<Listing[]>([]);
 const items=useMemo(()=>initial.filter(x=>{const p=x.card_printings;return p&&(game==="all"||p.game===game)&&`${p.canonical_name} ${p.set_name}`.toLowerCase().includes(query.toLowerCase())}),[initial,query,game]);
 const send=()=>{const lines=cart.map(x=>`1x ${x.card_printings?.canonical_name} ${x.card_printings?.collector_number} — ₡${x.approved_price_crc.toLocaleString("en-US")}`);const total=cart.reduce((n,x)=>n+x.approved_price_crc,0);const text=`Hola, quiero consultar disponibilidad:\n\n${lines.join("\n")}\n\nSubtotal: ₡${total.toLocaleString("en-US")}\nEntrega Duelist Kingdom: ₡500\n\nEntiendo que agregar al carrito no reserva las cartas.`;location.href=`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||"50671141906"}?text=${encodeURIComponent(text)}`};
 return <section id="catalogo"><div className="filters"><input className="input" placeholder="Buscar carta o set…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="select" value={game} onChange={e=>setGame(e.target.value)}><option value="all">Todos</option><option value="pokemon">Pokémon</option><option value="magic">Magic</option></select>{cart.length>0&&<button className="button" onClick={send}>Comprar por WhatsApp ({cart.length})</button>}</div><div className="grid">{items.map(x=>{const p=x.card_printings!;return <article className="product" key={x.id}><div className="art">{p.stock_image_url?<img src={p.stock_image_url} alt={p.canonical_name} style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<span>{p.canonical_name}<br/><small>{p.set_name}</small></span>}</div><div className="product-body"><span className="available">Disponible</span><h3>{p.canonical_name}</h3><div className="meta">{p.set_name} · {p.collector_number}<br/>{p.language} · {x.condition} · {x.finish}</div><div className="price">₡{x.approved_price_crc.toLocaleString("en-US")}</div><button className="button secondary" style={{marginTop:12}} onClick={()=>setCart(c=>c.some(i=>i.id===x.id)?c:c.concat(x))}>Agregar</button></div></article>})}</div>{items.length===0&&<div className="empty">No hay cartas publicadas todavía.</div>}</section>
}
